version: '3'
services:
        web:
                image: dnadynamite.stu
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8887:8887"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
